### ISSUE TITLE
Build/Dependency Problems

### ISSUE THREAD

**Issue by david-morris** [yikang-li/MSDN#14]
When trying to build faster_rcnn, I get the following error:

```
~/s/e/M/faster_rcnn> ./make.sh 
  File "setup.py", line 89
    print extra_postargs
                       ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(extra_postargs)?
Compiling roi pooling kernels by nvcc...
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    from torch.utils.ffi import create_extension
  File "/usr/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
```

Maybe the readme should explicitly state python2 if that is the issue?  Maybe a requirements.txt should  be made for making a conda environment if older versions of packages are needed?

I tried using a python=2.7 anaconda env, and got the same result.

**Comment by david-morris** [comment]
When I install pytorch<1.0, I get a different error.  This error persists when I change CUDA_PATH in make.sh:

```
./make.sh
running build_ext
skipping 'utils/bbox.c' Cython extension (up-to-date)
skipping 'utils/nms.c' Cython extension (up-to-date)
skipping 'nms/cpu_nms.c' Cython extension (up-to-date)
skipping 'nms/gpu_nms.cpp' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
Compiling roi pooling kernels by nvcc...
Including CUDA code.
/home/morris/src/examples/MSDN/faster_rcnn/roi_pooling
generating /tmp/tmpsuRm0v/_roi_pooling.c
setting the current directory to '/tmp/tmpsuRm0v'
running build_ext
building '_roi_pooling' extension
creating home
creating home/morris
creating home/morris/src
creating home/morris/src/examples
creating home/morris/src/examples/MSDN
creating home/morris/src/examples/MSDN/faster_rcnn
creating home/morris/src/examples/MSDN/faster_rcnn/roi_pooling
creating home/morris/src/examples/MSDN/faster_rcnn/roi_pooling/src
gcc -pthread -B /home/morris/.conda/envs/msdn2/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/morris/.conda/envs/msdn2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/morris/.conda/envs/msdn2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/morris/.conda/envs/msdn2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/home/morris/.conda/envs/msdn2/include/python2.7 -c _roi_pooling.c -o ./_roi_pooling.o -std=c99
In file included from /home/morris/.conda/envs/msdn2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4,                                                                                     
                 from _roi_pooling.c:493:
/home/morris/.conda/envs/msdn2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:10: fatal error: cuda.h: No such file or directory                                                 
 #include "cuda.h"
          ^~~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "build.py", line 34, in <module>
    ffi.build()
  File "/home/morris/.conda/envs/msdn2/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build                                                                                                 
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/morris/.conda/envs/msdn2/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension                                                                                      
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/morris/.conda/envs/msdn2/lib/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/morris/.conda/envs/msdn2/lib/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile                                                                                                     
    compiler_verbose, debug)
  File "/home/morris/.conda/envs/msdn2/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile                                                                                                        
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/morris/.conda/envs/msdn2/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build                                                                                                         
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
```

Where is CUDA_PATH supposed to be configured?

**Comment by yikang-li** [comment]
I cannot replicate the error. Maybe you can check our newest release project: https://github.com/yikang-li/FactorizableNet which supports Multi-GPU and support pytorch>=0.4.0.
